### ISSUE TITLE
Support non-CRD parents in Controller

### ISSUE THREAD

**Issue by nstogner** [codeformio/declare#6]
Currently the Controller spec assumed the parent is a CRD:

```yaml
spec:
  crdName: "..."
```

Allow for non-CRD parents. Perhaps the schema might look something like:

```yaml
spec:
  parent:
    group: ""
    kind: Namespace
    versions: ["v1"]
```
